[package]
name = "indexer-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
indexer-config = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
