[package]
name = "indexer-admin"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
indexer-config = { workspace = true }
indexer-data-model = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
